site_name: Documentation - Network Pro™
site_url: https://docs.netwk.pro/
repo_url: https://github.com/netwk-pro/netwk-pro.github.io
repo_name: GitHub
docs_dir: src
site_dir: build/

theme:
  name: material
  language: en
  font:
    text: null
    code: null
  logo: /icon-512x512.png
  favicon: /favicon.svg
  palette:
    # Default to dark mode
    - scheme: slate
      primary: amber
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Optional light mode
    - scheme: default
      primary: amber
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest

extra:
  base_url: /
  social:
    - icon: fontawesome/brands/instagram
      name: Network Pro on Instagram
      link: https://instagram.com/netwk_pro/
    - icon: fontawesome/brands/facebook
      name: Network Pro on Facebook
      link: https://facebook.com/neteng.pro/
    - icon: fontawesome/brands/linkedin
      name: Network Pro on LinkedIn
      link: https://linkedin.com/company/netwk-pro/
    - icon: fontawesome/brands/mastodon
      name: Network Pro on Mastodon
      link: https://noc.social/@neteng_pro/
    - icon: fontawesome/solid/at
      name: Contact Us
      link: https://netwk.pro/contact

copyright: >
  Copyright &copy; 2025 Network Pro Strategies (Network Pro&trade;) – This blog
  does not use cookies. See our <a href="https://netwk.pro/privacy">Privacy
  Policy</a> for details.

plugins:
  - privacy
  - search
  - meta
  - tags:
      tags_file: tags.md

nav:
  - About Us: README.md
  - Legal Documentation:
      - legal.md
      - privacy.md
      - terms-use.md
      - terms-conditions.md
  - Contributing:
      - Code of Conduct: conduct.md
      - Contribute to Network Pro™: contributing.md
  - Tags: tags.md
  - Blog: https://blog.netwk.pro
  - Back to Website: https://netwk.pro
