# Copyright © 2025 Network Pro Strategies (Network Pro™)
# SPDX-License-Identifier: CC-BY-4.0 OR GPL-3.0-or-later
# This file is part of Network Pro

blank_issues_enabled: true
contact_links:
  - name: 🐛 File a Bug Report
    url: https://github.com/netwk-pro/netwk-pro.github.io/issues/new?template=bug_report.yml
    about: Please open all bug reports in the main repository.

  - name: ✨ Feature Request
    url: https://github.com/netwk-pro/netwk-pro.github.io/issues/new?template=feature_request.yml
    about: Suggest new or updated features in the main repository.

  - name: ⚖️ Legal or Compliance Issue
    url: https://github.com/netwk-pro/netwk-pro.github.io/issues/new?template=legal_review.yml
    about: Raise legal or policy-related issues centrally.

  - name: Ask the Community
    url: https://discuss.neteng.pro
    about: Join the GitHub Discussions forum to get support from the community.

  - name: Stack Overflow (Internal Team)
    url: https://stack.neteng.pro
    about:
      Search or post questions in our internal Stack Overflow for Teams
      instance.

  - name: Contact Network Pro
    url: https://netwk.pro/contact?utm_source=github
    about: Contact us directly for help or private inquiries.
